---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: podinfo
  description: A podinfo service
  tags:
    - go
  annotations:
    github.com/project-slug: stefanprodan/podinfo
    backstage.io/kubernetes-id: podinfo
  links:
    - url: https://github.com/stefanprodan/podinfo
      title: Project
      icon: github
spec:
  type: service
  lifecycle: production
  owner: sockshop-team
  system: podinfo
  dependsOn:
    - resource:catalogue-db
  providesApis:
    - catalogue-api
