---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: podinfo
  description: Podinfo
  links:
    - url: https://example.com/catalog
      title: Catalog View
      icon: web
spec:
  owner: sockshop-team
  domain: podinfo
  partOf: system:sockshop
